export const projects = [
    {
        title: "Rempang Melayu Perkasa",
        description: "Website resmi Rempang Melayu Perkasa yang menampilkan profil dan layanan perusahaan.",
        tags: [],
        image: "/rempang.png",
        featured: true,
    },
    {
        title: "Bernardus Insight",
        description: "Website profil perusahaan dan layanan konsultasi bisnis yang profesional.",
        tags: [],
        image: "/bernadus.png",
        featured: true,
    },
    {
        title: "Dealer Hino Jakarta",
        description: "Website resmi dealer Hino Jakarta yang menampilkan produk truk, layanan purna jual, dan informasi kontak untuk pelanggan.",
        tags: [],
        image: "/hino.png",
        featured: false,
    },
    {
        title: "Spestama",
        description: "Website perusahaan Spestama yang menampilkan profil bisnis, layanan, dan informasi kontak secara profesional.",
        tags: [],
        image: "/spestama.png",
        featured: false,
    },
    {
        title: "Batu Alam Bekasi Murah",
        description: "Website toko batu alam di Bekasi yang menampilkan katalog produk, harga, dan informasi pemesanan.",
        tags: [],
        image: "/batualam.png",
        featured: false,
    },
    {
        title: "Harga Aion Jakarta",
        description: "Website resmi dealer mobil listrik Aion di Jakarta yang menampilkan harga, spesifikasi, dan promo terbaru.",
        tags: [],
        image: "/aionmobil.png",
        featured: false,
    },
    {
        title: "Gibran CCTV Jakarta-Bogor",
        description: "Website jasa pemasangan CCTV di area Jakarta dan Bogor dengan layanan profesional dan harga terjangkau.",
        tags: [],
        image: "/gibrancctv.png",
        featured: true,
    },
    {
        title: "Wuling Maju Jabodetabek",
        description: "Website dealer resmi Wuling di area Jabodetabek yang menampilkan produk mobil, harga, dan penawaran spesial.",
        tags: [],
        image: "/wuling.png",
        featured: false,
    },
    {
        title: "Hino Truk Jakarta",
        description: "Website resmi dealer Hino di Jakarta yang menampilkan katalog produk truk dan layanan purna jual.",
        tags: [],
        image: "/truk.png",
        featured: false,
    },
    {
        title: "Cetak Stempel Express",
        description: "Layanan pembuatan stempel kilat dan berkualitas secara online dengan pilihan desain yang beragam.",
        tags: [],
        image: "/stampel.png",
        featured: false,
    },
    {
        title: "Stempel.co.id",
        description: "Platform pemesanan stempel profesional dengan berbagai ukuran dan model untuk kebutuhan bisnis.",
        tags: [],
        image: "/stempel.png",
        featured: false,
    },
    {
        title: "Hipnoterapi Islami",
        description: "Layanan hipnoterapi berbasis nilai-nilai Islami untuk membantu mengatasi berbagai masalah psikologis.",
        tags: [],
        image: "/terapi.png",
        featured: false,
    },
    {
        title: "On Design and Build",
        description: "Perusahaan jasa desain arsitektur dan konstruksi bangunan yang profesional and terpercaya.",
        tags: [],
        image: "/rumah.png",
        featured: false,
    },
    {
        title: "Mulyo Tronik",
        description: "Website layanan servis alat elektronik dan penjualan suku cadang elektronik terlengkap.",
        tags: [],
        image: "/elek.png",
        featured: false,
    },
    {
        title: "Cuci Sofa Top",
        description: "Jasa pembersihan furnitur (sofa, karpet, kasur) profesional dengan hasil yang bersih dan higienis.",
        tags: [],
        image: "/cuci.png",
        featured: false,
    },

    {
        title: "Kriya Besi Nusantara",
        description: "Website jasa pengerjaan konstruksi besi dan las untuk berbagai kebutuhan properti.",
        tags: [],
        image: "/kriya.png",
        featured: false,
    },
    {
        title: "MI Tahfiz Al-Furqon",
        description: "Website resmi sekolah Madrasah Ibtidaiyah Tahfiz Al-Furqon untuk informasi akademik dan pendaftaran.",
        tags: [],
        image: "/mitafiz.png",
        featured: false,
    },
];
