export const projects = [
    {
        title: "Perpustakaan Online",
        description: "Sistem manajemen perpustakaan berbasis web untuk mengelola koleksi buku, peminjaman, dan pengembalian dengan fitur admin dan member yang lengkap.",
        tags: ["Next.js", "Tailwind CSS", "Prisma", "PostgreSQL"],
        image: "/perpus.png",
        githubUrl: "https://github.com/Hexheronjan/perpustkaan-online",
        liveUrl: "https://perpustkaan-online.vercel.app/",
        featured: true,
    },
    {
        title: "Sistem Inventaris Peminjaman Alat",
        description: "Sistem manajemen peminjaman alat berbasis web untuk mengelola inventaris, peminjaman, dan pengembalian dengan dashboard admin yang komprehensif.",
        tags: ["Next.js", "Tailwind CSS", "Prisma", "PostgreSQL"],
        image: "/peminjaman.png",
        githubUrl: "https://github.com/Hexheronjan/sistem-invertaris-peminjaman-alat",
        liveUrl: "https://sistem-invertaris-peminjaman-alat.vercel.app/",
        featured: true,
    },
    {
        title: "Dealer Hino Jakarta",
        description: "Website resmi dealer Hino Jakarta yang menampilkan produk truk, layanan purna jual, dan informasi kontak untuk pelanggan.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/hino.png",
        liveUrl: "https://www.dealerhinojkt.com/",
        featured: true,
    },
    {
        title: "Spestama",
        description: "Website perusahaan Spestama yang menampilkan profil bisnis, layanan, dan informasi kontak secara profesional.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/spestama.png",
        liveUrl: "https://spestama.co.id/",
        featured: false,
    },
    {
        title: "Batu Alam Bekasi Murah",
        description: "Website toko batu alam di Bekasi yang menampilkan katalog produk, harga, dan informasi pemesanan.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/batualam.png",
        liveUrl: "https://batualambekasimurah.com/",
        featured: false,
    },
    {
        title: "Harga Aion Jakarta",
        description: "Website resmi dealer mobil listrik Aion di Jakarta yang menampilkan harga, spesifikasi, dan promo terbaru.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/aionmobil.png",
        liveUrl: "https://hargaaionjakarta.com/",
        featured: false,
    },
    {
        title: "Gibran CCTV Jakarta-Bogor",
        description: "Website jasa pemasangan CCTV di area Jakarta dan Bogor dengan layanan profesional dan harga terjangkau.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/gibrancctv.png",
        liveUrl: "https://gibrancctvjakarta-bogor.com/",
        featured: false,
    },
    {
        title: "Wuling Maju Jabodetabek",
        description: "Website dealer resmi Wuling di area Jabodetabek yang menampilkan produk mobil, harga, dan penawaran spesial.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/wuling.png",
        liveUrl: "https://wulingmajujabodetabek.com/",
        featured: false,
    },
    {
        title: "Hino Truk Jakarta",
        description: "Website resmi dealer Hino di Jakarta yang menampilkan katalog produk truk dan layanan purna jual.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/truk.png",
        liveUrl: "https://hino-trukjakarta.com/",
        featured: false,
    },
    {
        title: "Cetak Stempel Express",
        description: "Layanan pembuatan stempel kilat dan berkualitas secara online dengan pilihan desain yang beragam.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/stampel.png",
        liveUrl: "https://cetakstempelexpress.com/",
        featured: false,
    },
    {
        title: "Stempel.co.id",
        description: "Platform pemesanan stempel profesional dengan berbagai ukuran dan model untuk kebutuhan bisnis.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/stempel.png",
        liveUrl: "https://stempel.co.id/",
        featured: false,
    },
    {
        title: "Hipnoterapi Islami",
        description: "Layanan hipnoterapi berbasis nilai-nilai Islami untuk membantu mengatasi berbagai masalah psikologis.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/terapi.png",
        liveUrl: "https://hipnoterapiislami.com/",
        featured: false,
    },
    {
        title: "On Design and Build",
        description: "Perusahaan jasa desain arsitektur dan konstruksi bangunan yang profesional dan terpercaya.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/rumah.png",
        liveUrl: "https://ondesignandbuild.com/",
        featured: false,
    },
    {
        title: "Mulyo Tronik",
        description: "Website layanan servis alat elektronik dan penjualan suku cadang elektronik terlengkap.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/elek.png",
        liveUrl: "https://mulyotronik.com/",
        featured: false,
    },
    {
        title: "Cuci Sofa Top",
        description: "Jasa pembersihan furnitur (sofa, karpet, kasur) profesional dengan hasil yang bersih dan higienis.",
        tags: ["WordPress", "PHP", "CSS"],
        image: "/cuci.png",
        liveUrl: "https://cucisofatop.co.id/",
        featured: false,
    },
];
